name: tictacoe
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-333.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: AudioWide
      fonts:
        - asset: assets/fonts/audio_wide/Audiowide-Regular.ttf
    - family: GeostarFill
      fonts:
        - asset: assets/fonts/geo_star/GeostarFill-Regular.ttf
